### ISSUE TITLE
Small bug in GLSL code generation 

### ISSUE THREAD

**Issue by cherudim9** [csyonghe/Spire#9]
[This line](https://github.com/csyonghe/Spire/blob/master/Source/SpireCore/GLSLCodeGen.cpp#L238) should be modified as:
`if (op0->Type->IsVector() && !op0->Type->IsFloatMatrix())`

Otherwise, given `mat3 a; float b=a[1][1];` Spire will generate code like `b=a.x.x;`.

**Comment by csyonghe** [comment]
That is allowed in GLSL.

Yong

On Tue, Jul 26, 2016 at 11:00 AM -0700, "cherudim9" notifications@github.com wrote:

[This line](https://github.com/csyonghe/Spire/blob/master/Source/SpireCore/GLSLCodeGen.cpp#L238) should be modified as:
`if (op0->Type->IsVector() && !op0->Type->IsFloatMatrix())`

Otherwise, given `mat3 a; float b=a[1][1];` Spire will generate code like `b=a.x.x;`.

---

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/csyonghe/Spire/issues/9

**Comment by cherudim9** [comment]
I thought it was wrong because this kind of syntax failed to pass GLSLangValidator :( You are right.

**Comment by vczh** [comment]
@csyonghe 难道原来不是float的matrix就可以这么写吗，为什么要单独指出是float matrix

**Comment by csyonghe** [comment]
哦，暂时没支持int matrix，反正没人用，懒。

Yong

On Fri, Jul 29, 2016 at 4:56 AM -0400, "Zihan Chen" notifications@github.com wrote:

@csyonghe 难道原来不是float的matrix就可以这么写吗，为什么要单独指出是float matrix

---
